---
- name: Test software installation on Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure 7-Zip is installed through Chocolatey
      win_chocolatey:
        name: 7zip
        state: present
