---
- name: Test software installation on Windows
  hosts: all
  become: false
  gather_facts: false
  vars:
    - packages:
      - git
      - notepadplusplus
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
        # check if git and notepad++ is installed. If not, chocolatey will install them
        state: present
